[build]
  command = "pnpm run build"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/:path.:ext"
  to = "/:path.:ext"
  status = 200

[[redirects]]
  from = "/koloruj"
  to = "/koloruj/"
  status = 301
  force = true

[[redirects]]
  from = "/koloruj/*"
  to = "/koloruj/"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[headers]]
  for = "/koloruj/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/*"
  [headers.values]
    X-Debug-Edge = "on"
