[build.environment]
  NODE_VERSION = "20"

[build]
  command = "pnpm build"
  publish = ".output/public"

[[redirects]]
  from = "/koloruj"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/koloruj/*"
  to = "/index.html"
  status = 200
