[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/koloruj"
  to = "/koloruj/"
  status = 301
  force = false

[[redirects]]
  from = "/koloruj/*"
  to = "/koloruj/"
  status = 200

[[redirects]]
  from = "/:dir"
  to = "/:dir/"
  status = 301
  force = false

[[redirects]]
  from = "/:dir/:sub"
  to = "/:dir/:sub/"
  status = 301
  force = false

[[redirects]]
  from = "/:dir/:sub/:leaf"
  to = "/:dir/:sub/:leaf/"
  status = 301
  force = false

[[redirects]]
  from = "/:a/:b/:c/:d"
  to = "/:a/:b/:c/:d/"
  status = 301
  force = false

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
